#!/usr/bin/env python3
"""Trace an insightface buffalo pack and emit a verbatim tensor-name manifest.

This is the FIRST converter-side artifact: it enumerates, per sub-model, the
*exact* ONNX initializer names (no renaming) plus shape / dtype / the ggml `ne`
(reversed shape) and the selective-quant decision that
``scripts/convert_facedetect_to_gguf.py`` will apply. Every later graph/converter
task maps these verbatim names 1:1 into ggml, so this manifest is the contract.

Usage:
    python scripts/trace_onnx_manifest.py [--model buffalo_l] [--dtype f16] \
        [--out scripts/tensor_manifest_buffalo_l.md]

It resolves the pack the same way the converter does (``resolve_pack``), so the
file set it documents is exactly the file set the converter reads.
"""
import argparse
import os
import sys

import numpy as np
import onnx
from onnx import numpy_helper


# Mirror of scripts/convert_facedetect_to_gguf.py:should_quantize so the manifest
# documents the *actual* quant decision the converter makes. Keep in sync.
def should_quantize(name, arr, dtype):
    import gguf
    if dtype == "f32" or arr.ndim < 2:
        return None
    ggml_ne = list(arr.shape[::-1])          # ggml ne is the reversed shape
    if ggml_ne[0] < 32 or ggml_ne[1] < 32:
        return None
    if dtype == "f16":
        return gguf.GGMLQuantizationType.F16
    if dtype == "q8_0":
        return None if ggml_ne[0] % 32 else gguf.GGMLQuantizationType.Q8_0
    return None


def resolve_pack(model):
    import glob
    base = model if os.path.isdir(model) else \
        os.path.expanduser(f"~/.insightface/models/{model}")

    def find(pat):
        hits = glob.glob(os.path.join(base, "**", pat), recursive=True)
        return hits[0] if hits else None

    det = find("det_*.onnx")
    rec = find("w600k_*.onnx")
    if not det or not rec:
        return None
    return dict(
        base=base, det_onnx=det, rec_onnx=rec,
        genderage_onnx=find("genderage.onnx"),
        antispoof=sorted(glob.glob(
            os.path.join(base, "**", "MiniFASNet*.onnx"), recursive=True)),
    )


def io_shapes(m):
    def dims(vi):
        return [d.dim_value for d in vi.type.tensor_type.shape.dim]
    ins = [(vi.name, dims(vi)) for vi in m.graph.input]
    outs = [(vi.name, dims(vi)) for vi in m.graph.output]
    return ins, outs


def trace_submodel(title, kind, onnx_path, dtype, skip_q, prefix):
    m = onnx.load(onnx_path)
    ins, outs = io_shapes(m)
    rows = []
    n_quant = 0
    n_skip_scalar = 0
    for init in m.graph.initializer:
        arr = np.ascontiguousarray(numpy_helper.to_array(init), dtype=np.float32)
        onnx_dt = onnx.TensorProto.DataType.Name(init.data_type)
        gguf_name = prefix + init.name
        if arr.ndim == 0:
            # scalars are bookkeeping; the converter skips them entirely
            n_skip_scalar += 1
            rows.append((gguf_name, init.name, "()", onnx_dt, "-", "skip (scalar)"))
            continue
        ggml_ne = list(arr.shape[::-1])
        qt = None if skip_q else should_quantize(init.name, arr, dtype)
        if qt is None:
            decision = "F32 (verbatim)"
        else:
            decision = qt.name
            n_quant += 1
        rows.append((gguf_name, init.name, str(list(init.dims)), onnx_dt,
                     str(ggml_ne), decision))
    return dict(title=title, kind=kind, path=onnx_path, ins=ins, outs=outs,
                prefix=prefix, rows=rows, n_quant=n_quant, n_scalar=n_skip_scalar)


def md_table(rows):
    out = ["| GGUF tensor name | ONNX initializer | ONNX shape | ONNX dtype | ggml `ne` | quant @ f16 |",
           "|---|---|---|---|---|---|"]
    for gguf_name, onnx_name, shp, dt, ne, dec in rows:
        out.append(f"| `{gguf_name}` | `{onnx_name}` | `{shp}` | {dt} | `{ne}` | {dec} |")
    return "\n".join(out)


def emit(packname, dtype, sub):
    lines = []
    lines.append(f"# {packname} tensor-name manifest (verbatim ONNX initializers)")
    lines.append("")
    lines.append("> Generated by `scripts/trace_onnx_manifest.py`. This is the converter")
    lines.append("> contract: `scripts/convert_facedetect_to_gguf.py` writes every")
    lines.append("> initializer below into the GGUF under a stable per-sub-model")
    lines.append("> namespace prefix (`det.` / `rec.` / `ga.` / `as<i>.`), keeping the")
    lines.append("> ONNX name otherwise **verbatim**. Every C++/ggml graph task maps the")
    lines.append("> GGUF tensor name 1:1. Do not rename. The prefix is required because")
    lines.append("> buffalo's SCRFD and ArcFace ONNX graphs reuse auto-numbered")
    lines.append("> initializer names (`685`, `689`, `691`, `695`, `697`, `701`) for")
    lines.append("> different real weights, and the C++ loader keys all tensors by name")
    lines.append("> in one ggml context.")
    lines.append("")
    lines.append("## Provenance")
    lines.append("")
    lines.append(f"- Pack: `{packname}` (insightface "
                 "`deepinsight/insightface` release v0.7).")
    lines.append("- **License: non-commercial** (insightface model release terms). The")
    lines.append("  weights are used here only to trace tensor names; the commercial-")
    lines.append("  friendly alternative is the YuNet + SFace pack (Apache-2.0).")
    lines.append(f"- Download: `{packname}.zip` from the insightface v0.7 release.")
    lines.append(f"- Quant column reflects `--dtype {dtype}` (the converter default).")
    lines.append("- All source initializers are ONNX `FLOAT` (F32); quantization is")
    lines.append("  applied by the converter on 2-D+ weights only. With the brief's")
    lines.append("  `should_quantize`, a tensor qualifies only when **both** of its two")
    lines.append("  innermost ggml `ne` dims are >= 32, so 3x3 / 1x1 conv kernels")
    lines.append("  (innermost `ne` = 3 or 1) stay F32 and only large 2-D Gemm/MatMul")
    lines.append("  weights (e.g. the ArcFace embedding `fc`) are stored F16/Q8_0.")
    lines.append("")
    lines.append("## Sub-model file set (as resolved by `resolve_pack`)")
    lines.append("")
    lines.append("| role | file | GGUF prefix | initializers | quantized @ f16 | scalars skipped |")
    lines.append("|---|---|---|---:|---:|---:|")
    for s in sub:
        lines.append(f"| {s['kind']} | `{os.path.basename(s['path'])}` | "
                     f"`{s['prefix']}` | {len(s['rows'])} | {s['n_quant']} | {s['n_scalar']} |")
    lines.append("")
    lines.append("> Note: buffalo_l also ships `1k3d68.onnx` (3D-68 landmark) and")
    lines.append("> `2d106det.onnx` (2D-106 landmark). The SCRFD+ArcFace recognition")
    lines.append("> pipeline does **not** consume them (SCRFD emits its own 5-point")
    lines.append("> landmarks used by `norm_crop`), so they are not converted. buffalo_l")
    lines.append("> ships **no** MiniFASNet anti-spoof ONNX, so `facedetect.antispoof.*`")
    lines.append("> is absent for this pack.")
    lines.append("")
    for s in sub:
        lines.append(f"## {s['title']}")
        lines.append("")
        lines.append(f"- File: `{os.path.basename(s['path'])}`")
        lines.append("- Inputs: " + ", ".join(
            f"`{n}` `{d}`" for n, d in s['ins']))
        lines.append("- Outputs: " + ", ".join(
            f"`{n}` `{d}`" for n, d in s['outs']))
        lines.append(f"- Initializers: {len(s['rows'])} "
                     f"({s['n_quant']} quantized @ f16, {s['n_scalar']} scalars skipped)")
        lines.append("")
        lines.append(md_table(s['rows']))
        lines.append("")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="buffalo_l")
    ap.add_argument("--dtype", default="f16", choices=["f32", "f16", "q8_0"])
    ap.add_argument("--out", default=None)
    args = ap.parse_args()

    pack = resolve_pack(args.model)
    if pack is None:
        print(f"trace: pack {args.model!r} not found under ~/.insightface/models",
              file=sys.stderr)
        sys.exit(2)

    det_name = os.path.splitext(os.path.basename(pack["det_onnx"]))[0]
    rec_name = os.path.splitext(os.path.basename(pack["rec_onnx"]))[0]
    is_mbf = "mbf" in rec_name.lower()
    rec_desc = "MobileFaceNet, 512-d" if is_mbf else "ResNet50, 512-d"
    sub = [
        trace_submodel(f"SCRFD detector (`{det_name}`)", "scrfd detector",
                       pack["det_onnx"], args.dtype, skip_q=False, prefix="det."),
        trace_submodel(f"ArcFace recognizer (`{rec_name}`, {rec_desc})",
                       "arcface recognizer", pack["rec_onnx"], args.dtype,
                       skip_q=False, prefix="rec."),
    ]
    if pack.get("genderage_onnx"):
        sub.append(trace_submodel("GenderAge head (`genderage`)", "genderage",
                                  pack["genderage_onnx"], args.dtype, skip_q=True,
                                  prefix="ga."))
    for i, asp in enumerate(pack.get("antispoof", [])):
        sub.append(trace_submodel(f"Anti-spoof (`{os.path.basename(asp)}`)",
                                  "antispoof", asp, args.dtype, skip_q=True,
                                  prefix=f"as{i}."))

    md = emit(args.model, args.dtype, sub)
    out = args.out or os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                   f"tensor_manifest_{args.model}.md")
    with open(out, "w") as f:
        f.write(md)
    total = sum(len(s['rows']) for s in sub)
    print(f"trace: wrote manifest for {len(sub)} sub-models, {total} initializers "
          f"-> {out}", file=sys.stderr)


if __name__ == "__main__":
    main()
